package ie.tcd.kdeg.entities;


public enum TypeOfResource {
		TEXT, 
		CARTOGRAPHIC, 
		NOTATED_MUSIC, 
		SOUND_RECORDING, 
		SOUND_RECORDING_MUSICAL, 
		SOUND_RECORDING_NONMUSICAL, 
		STILL_IMAGE, 
		MOVING_IMAGE, 
		THREE_DIMENSIONAL_OBJECT, 
		SOFTWARE_MULTIMEDIA, 
		MIXED_MATERIAL;
	
	 
}

